# Generated by Django 4.2.6 on 2023-10-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='employee_size',
            field=models.IntegerField(),
        ),
    ]
